# Generated by Django 4.2.6 on 2023-11-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
                ('estilo_prenda', models.CharField(max_length=100)),
                ('color_prenda', models.CharField(max_length=50)),
            ],
        ),
    ]
