# Generated by Django 4.2.6 on 2023-11-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='color_prenda',
            field=models.CharField(choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Beige', 'Beige'), ('Gris', 'Gris'), ('Azul', 'Azul')], max_length=50),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='estilo_prenda',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Deportivo', 'Deportivo'), ('Elegante', 'Elegante'), ('Urbano', 'Urbano')], max_length=100),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50),
        ),
    ]
