# Generated by Django 4.2.6 on 2023-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_alter_outfit_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='corazones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
