# Generated by Django 4.2.6 on 2023-11-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0005_outfit_comentarios_outfit_corazones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='corazones',
            new_name='cantidad_corazones',
        ),
    ]
