# Generated by Django 4.2.6 on 2023-11-18 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfits', '0006_rename_corazones_outfit_cantidad_corazones'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='usuarios_que_dieron_corazon',
            field=models.ManyToManyField(blank=True, related_name='corazones_dados', to=settings.AUTH_USER_MODEL),
        ),
    ]
