# Generated by Django 4.2.6 on 2023-11-18 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfits', '0007_outfit_usuarios_que_dieron_corazon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='comentarios',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfits.outfit')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='comentarios', through='outfits.Comentario', to=settings.AUTH_USER_MODEL),
        ),
    ]
