# Generated by Django 4.2.6 on 2023-11-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0008_remove_outfit_comentarios_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.AddField(
            model_name='outfit',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
