# Generated by Django 4.2.6 on 2023-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0010_remove_outfit_comentarios_comment_outfit_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='outfit',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
    ]
